# Generated by Django 4.2.7 on 2023-12-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='executive',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
